# === NETWORK ===
listenAddress:
  ipv4: "0.0.0.0"
  ipv6: "::"

protocol:
  ipv4: true
  ipv6: false

port: 8000
listen: true

# === SECURITY ===
enableForwardedWhitelist: false

whitelist: []

whitelistDockerHosts: false

hostWhitelist:
  enabled: false

basicAuthMode: true

basicAuthUser:
  username: admin
  password: changeme

enableUserAccounts: false

disableCsrfProtection: true

securityOverride: true

# === DATA ===
dataRoot: "./data"

# === LOGS ===
logging:
  enableAccessLog: true
  minLogLevel: info
